### PR TITLE
adds definition for quiz parameters

### PR DESCRIPTION
**Pull request by Elorfin**
Related to #26 

I've made some little changes : 
- The `parameters` property is required. We can not play a quiz without it.
- Each parameter is also required.
- We can not remove `keepSteps` because it is used by `random` and `pick`. I've renamed it in `draw` and it's an `enum(once|attempt)`.

### CODE REVIEW

**Comment by stefk** [comment]
> The parameters property is required. We can not play a quiz without it.
Each parameter is also required.

I don't understand the reasonning behind that. That would make the definition extremely verbose and practically useless outside our particular project. If we're able to provide a default value for each of these parameters, why would we force specifying them?

> We can not remove keepSteps because it is used by random and pick

Can you explain what's wrong with the proposal in #26 on this subject?

**Comment by Elorfin** [comment]
> If we're able to provide a default value for each of these parameters, why would we force specifying them?

You are right, in fact all the properties have default values. I will change it.

**Comment by Elorfin** [comment]
Parameters are now optionals.

**Comment by Elorfin** [comment]
`random`
`pick`
`draw`

have been replaced by

`randomOrder(enum)`: once|never|always
`randomPick(enum)`: once|never|always
`pick(number)`

**Pull request merged**
