### PR TITLE
add score property to Questions

### PR DESCRIPTION
**Pull request by Elorfin**
It must be a Number (> 0) and is optional.

### CODE REVIEW

**Comment by Elorfin** [comment]
Tests and Examples have been updated, but I don't know how I can update the github.io site.

**Comment by stefk** [comment]
I'm not sure this is a good idea. Considering how individual question types are designed, the score is actually more a computed value (i.e. the sum of the maximal score of each item in the question -- choices, holes, associations, etc.). That new `score` property doesn't add anything we can't already deduce from the question definition. There's also a risk of having a mismatch between its value and the actual sum of item scores.

What do you think?

**Comment by Elorfin** [comment]
I'm OK with that. 

That was to manage [UJM/ExoBundle](https://github.com/UJM/ExoBundle) API which returns the total score of a Question and so fails the schema validation.

I will create a service in my client to calculate Question score based on its type so the spec will remain the same.

**Comment by Elorfin** [comment]
I'm reading the specification and I'm thinking of something : for all types, the scores are only exposed in the `solutions` property, so when you export your exercise without it (which is, I think, generally the case for security purpose) you can not access the total score of the question.

Is there going to be use cases where we will need the total score before loading the solutions ? For example, if we want to show the User how many points he can have for this question during his attempt.

**Comment by stefk** [comment]
> UJM/ExoBundle API [...] returns the total score of a Question and so fails the schema validation.

Are you sure? AFAIK additional properties are allowed in the base question schema, so even if it's not part of the spec, adding a property like this one for practical purposes should be valid.

**Comment by stefk** [comment]
> Is there going to be use cases where we will need the total score before loading the solutions ?

Good point.

**Comment by Elorfin** [comment]
> Are you sure? AFAIK additional properties are allowed in the base question schema, so even if it's not part of the spec, adding a property like this one for practical purposes should be valid.

You are right. The test does not pass because the property is not set in static JSON files that are used in the test suite, so the comparison between the exported question and the static file fails.

**Pull request closed without merging**
